# Scientific libraries: Numpy

In [1]:
# pip install numpy
# conda install numpy
# !uv pip install numpy

Using Python 3.14.0 environment at: /Users/fca3004vt25/course/.venv
Resolved 1 package in 133ms                                          
Prepared 1 package in 264ms                                              
Installed 1 package in 13ms                                 
 + numpy==2.3.5


In [3]:
import numpy as np

In [4]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x109131850>
File:            ~/course/.venv/lib/python3.14/site-packages/numpy/_core/function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    I

In [10]:
x = np.linspace(0, 1)
x

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [11]:
y = x * x
y

array([0.00000000e+00, 4.16493128e-04, 1.66597251e-03, 3.74843815e-03,
       6.66389005e-03, 1.04123282e-02, 1.49937526e-02, 2.04081633e-02,
       2.66555602e-02, 3.37359434e-02, 4.16493128e-02, 5.03956685e-02,
       5.99750104e-02, 7.03873386e-02, 8.16326531e-02, 9.37109538e-02,
       1.06622241e-01, 1.20366514e-01, 1.34943773e-01, 1.50354019e-01,
       1.66597251e-01, 1.83673469e-01, 2.01582674e-01, 2.20324865e-01,
       2.39900042e-01, 2.60308205e-01, 2.81549354e-01, 3.03623490e-01,
       3.26530612e-01, 3.50270721e-01, 3.74843815e-01, 4.00249896e-01,
       4.26488963e-01, 4.53561016e-01, 4.81466056e-01, 5.10204082e-01,
       5.39775094e-01, 5.70179092e-01, 6.01416077e-01, 6.33486047e-01,
       6.66389005e-01, 7.00124948e-01, 7.34693878e-01, 7.70095793e-01,
       8.06330696e-01, 8.43398584e-01, 8.81299459e-01, 9.20033319e-01,
       9.59600167e-01, 1.00000000e+00])

In [15]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [16]:
np.arange(0, 1, .2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [17]:
la=[1.,2.,3.]
lb=[4., 5., 6.]

In [18]:
np.array([la, lb])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
%%file a.dat
1 2 3
4 5 6

Writing a.dat


In [21]:
amatrix = np.loadtxt('a.dat')
amatrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
np.savetxt('b.dat', amatrix)

In [27]:
!cat b.dat

1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00


In [28]:
amatrix.shape

(2, 3)

In [30]:
bmatrix = amatrix.reshape((3, 2))
bmatrix

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [31]:
bmatrix[0] # the first row

array([1., 2.])

In [32]:
bmatrix[0, 0]

np.float64(1.0)

In [33]:
bmatrix[0, 0] = 0.0

In [34]:
bmatrix

array([[0., 2.],
       [3., 4.],
       [5., 6.]])

In [35]:
amatrix

array([[0., 2., 3.],
       [4., 5., 6.]])

In [37]:
# enumerate in python

for i in ['a', 'b', 'c']:
    print(i)

a
b
c


In [40]:
# if we want the index

for i, value in enumerate(['a', 'b', 'c'], start=1):
    print(i, value)

1 a
2 b
3 c


In [42]:
# np.enumerate
for i in np.ndenumerate(amatrix):
    print(i)

((0, 0), np.float64(0.0))
((0, 1), np.float64(2.0))
((0, 2), np.float64(3.0))
((1, 0), np.float64(4.0))
((1, 1), np.float64(5.0))
((1, 2), np.float64(6.0))


In [43]:
for (row, col), value in np.ndenumerate(amatrix):
    print(row)
    print(col)
    print(value)

0
0
0.0
0
1
2.0
0
2
3.0
1
0
4.0
1
1
5.0
1
2
6.0


## Matrix multiplication

$$ C_{ij} = \sum_k A_{ik} B_{kj} $$

In [99]:
import  time
n=512
a=numpy.ones((n,n))
b=numpy.ones((n,n))
c=numpy.zeros((n,n))
t1=time.time()
for i in range(n):
   for j in range(n):
       for k in range(n):
           c[i,j]+=a[i,k]*b[k,j]
t2=time.time()
print("Loop timing",t2-t1)

Loop timing 36.418989181518555


In [100]:
a=numpy.ones((n,n))
b=numpy.ones((n,n))
c=numpy.zeros((n,n))
t1=time.time()
c = a @ b
t2=time.time()
print("Loop timing",t2-t1)

Loop timing 0.009280920028686523


In [101]:
%%file example.F90
INTEGER, PARAMETER :: N = 512 
REAL*8, DIMENSION(N,N) :: A, B, C
! Timing
INTEGER :: T1, T2, RATE
! Initialize
A = 1.0
B = 1.0
!
CALL SYSTEM_CLOCK(COUNT_RATE=RATE)
CALL SYSTEM_CLOCK(COUNT=T1)
C = MATMUL(A, B)
CALL SYSTEM_CLOCK(COUNT=T2)
PRINT '(A, F6.3)', 'MATMUL timing',  DBLE(T2-T1)/RATE
END

Overwriting example.F90


In [102]:
!/opt/homebrew/bin/gfortran example.F90 -o example.x

In [103]:
!./example.x

MATMUL timing 0.018


In [54]:
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(250, 250))

In [55]:
a * 2

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], shape=(250, 250))

In [56]:
a * a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(250, 250))

In [57]:
a @ a

array([[250., 250., 250., ..., 250., 250., 250.],
       [250., 250., 250., ..., 250., 250., 250.],
       [250., 250., 250., ..., 250., 250., 250.],
       ...,
       [250., 250., 250., ..., 250., 250., 250.],
       [250., 250., 250., ..., 250., 250., 250.],
       [250., 250., 250., ..., 250., 250., 250.]], shape=(250, 250))

In [61]:
import math
def f(x):
    return math.sqrt(x + 1)

In [62]:
f(3.5)

2.1213203435596424

In [63]:
f(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [65]:
@np.vectorize
def f(x):
    return math.sqrt(x + 1)

In [66]:
f(a)

array([[1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356],
       [1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356],
       [1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356],
       ...,
       [1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356],
       [1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356],
       [1.41421356, 1.41421356, 1.41421356, ..., 1.41421356, 1.41421356,
        1.41421356]], shape=(250, 250))

## more linear algebra

In [68]:
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_linalg',
 '_umath_linalg',
 'cholesky',
 'cond',
 'cross',
 'det',
 'diagonal',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'linalg',
 'lstsq',
 'matmul',
 'matrix_norm',
 'matrix_power',
 'matrix_rank',
 'matrix_transpose',
 'multi_dot',
 'norm',
 'outer',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'svdvals',
 'tensordot',
 'tensorinv',
 'tensorsolve',
 'test',
 'trace',
 'vecdot',
 'vector_norm']

In [70]:
A = np.array([[1, 2], [3, 4]]); b=np.array([5, 6])

In [71]:
A

array([[1, 2],
       [3, 4]])

In [72]:
b

array([5, 6])

## solve Ax = b

In [73]:
x = np.linalg.solve(A, b)

In [74]:
x

array([-4. ,  4.5])

In [75]:
A @ x

array([5., 6.])

In [78]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [79]:
np.linalg.inv(A) @ A

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [80]:
# eigenvalues

In [82]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [84]:
l, x =  np.linalg.eig(A)

In [85]:
l

array([-0.37228132,  5.37228132])

In [86]:
x

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [87]:
A @ x[:, 0]

array([ 0.30697009, -0.21062466])

In [88]:
x[:, 0] * l[0]

array([ 0.30697009, -0.21062466])

## filtering data

In [104]:
v = np.array([1, 2, -3, 4, 5])

In [105]:
v > 0

array([ True,  True, False,  True,  True])

In [106]:
v[ v > 0 ]

array([1, 2, 4, 5])